{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "react-frontend.fullname" . }}-env
  labels:
    {{- include "react-frontend.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.storeRef.name }}
    kind: {{ .Values.externalSecret.storeRef.kind }}
  target:
    name: {{ include "react-frontend.fullname" . }}-env
  data:
    {{- toYaml .Values.externalSecret.data | nindent 4 }}
{{- end }}
